<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SABYA-TI8237" name="com.taxiforsure.testCases.FairChartTest" tests="5" failures="0" timestamp="1 Oct 2014 10:17:26 GMT" time="32.717" errors="1">
  <testcase name="fairChartPointToPointDayTest" time="6.404" classname="com.taxiforsure.testCases.FairChartTest">
    <error type="java.lang.AssertionError" message="expected [143.0] but found [14.0]">
      <![CDATA[java.lang.AssertionError: expected [143.0] but found [14.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.taxiforsure.testCases.FairChartTest.fairChartPointToPointDayTest(FairChartTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- fairChartPointToPointDayTest -->
  <testcase name="fairChartPointToPointDayTest" time="6.497" classname="com.taxiforsure.testCases.FairChartTest"/>
  <testcase name="fairChartPointToPointDayTest" time="6.457" classname="com.taxiforsure.testCases.FairChartTest"/>
  <testcase name="fairChartPointToPointDayTest" time="6.901" classname="com.taxiforsure.testCases.FairChartTest"/>
  <testcase name="fairChartPointToPointDayTest" time="6.458" classname="com.taxiforsure.testCases.FairChartTest"/>
</testsuite> <!-- com.taxiforsure.testCases.FairChartTest -->
